config/routes.rb
BEF::Application.routes.draw do
  resources :events
  resources :people
  resources :distinguish_badgers, only: [:index, :show]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'mentors', to: 'people#mentors'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise \
    :database_authenticatable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable
end

app/models/distinguish_badger.rb
class DistinguishBadger < ActiveRecord::Base

	validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :photo, styles: { large: '300x300', medium: '200x200', thumb: '100x100' }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  just_define_datetime_picker :starts_at

  validates :starts_at, presence: true
  validates :title, presence: true

  has_attached_file :photo, styles: { huge: '1200x600#', large: '600x300#', medium: '300x200#', thumb: '100x66#' }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  default_scope { order('events.starts_at desc') }

  def self.next_or_last
    if upcoming_events.any?
      upcoming_events.first
    else
      past_events.first
    end
  end

  def self.published
    where(published: true)
  end

  def self.past_events
    published.where('starts_at is not null and starts_at <= ?', Time.now)
  end

  def self.upcoming_events
    published.where('starts_at is not null and starts_at >= ?', Time.now).order('events.starts_at asc')
  end

  def self.without(event)
    return self unless event
    where('id != :id', id: event.id)
  end

  def past?
    starts_at.past?
  end

  def truncate_desc(max_sentences = 3, max_words = 50)
    # Take first 3 setences
    three_sentences = description ? description.gsub(/&.*;/,'').scan(/[^\.!?]+[\.!?]/).map(&:strip)[0..max_sentences-1].join(' ') : ''
    # Take first 50 words of the above
    three_sentences.split(' ').slice(0, max_words).join(' ')
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :roles
  has_many :tags, through: :roles

  accepts_nested_attributes_for :roles

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :photo, styles: { large: '300x300', medium: '200x200', thumb: '100x100' }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  default_scope { order(:last_name) }

  def display_name
    decorate.full_name
  end

  def self.mentors
    where(mentor: true)
  end

  def self.board_members
    where(board_member: true)
  end

  def self.for_tag_title(tag_title)
    return all unless tag_title.present?

    joins(:tags).where(tags: { title: tag_title })
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :person
  belongs_to :tag
end

app/models/settings.rb
class Settings
  extend Chamber

  # source Rails.root.join('config', 'settings.yml'), namespace: Rails.env, override_from_environment: true
  # source Rails.root.join('config', "credentials-#{Rails.env}.yml")

  # load!
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :roles
  has_many :people, through: :roles

  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/distinguish_badgers_controller.rb
class DistinguishBadgersController < ApplicationController
	expose(:distinguish_people) { DistinguishBadger.all.order('date DESC').decorate }

	def index ;end

	def show; end
	
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  expose(:events) { Event.published.decorate }
  expose(:event) { Event.where(slug: params[:id]).first.decorate }

  def index
  end

  def show
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  expose(:raw_selected_tag) { Tag.where(title: tag_title).first }
  expose(:selected_tag) { raw_selected_tag.decorate if raw_selected_tag }
  expose(:tags) { Tag.all.decorate }
  expose(:tag_title) { params[:tag_title] }
  expose(:people) { Person.for_tag_title(tag_title).decorate }
  expose(:badger_mentors) { Person.mentors.decorate }

  def index
  end

  def mentors
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  expose(:board_members) { Person.board_members.decorate }
  expose(:past_events) { Event.past_events.without(raw_event).limit(3).decorate }
  expose(:event) { raw_event.decorate if raw_event }
  expose(:raw_event) { Event.next_or_last }

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(name, path)
    klass = 'active' if current_page?(path)

    content_tag(:li, link_to(name, path), class: klass)
  end
end

app/helpers/people_helper.rb
module PeopleHelper

	def person person_id
		@person = Person.find(person_id)
	end

	def short_person_date date
		date.strftime("%B %-d, %Y")
	end
	
end

app/views/admin/people/_linkedin_sidebar.html.haml
- if @distinguish_badger || @person.linkedin_url.present?
  <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
  <script type="IN/MemberProfile" data-id="#{@distinguish_badger || @person.linkedin_url}" data-format="inline" data-related="false" data-width="300"></script>

app/views/distinguish_badgers/index.html.haml
= content_for :title, 'Distinguished Badgers'

%h1 Distinguished Badgers
.events
	- distinguish_people.each do |distinguish_badger|
		.row.event
			.col-md-4
				- if distinguish_badger.photo.exists?
					.image
						= link_to(image_tag(distinguish_badger.photo.url(:medium)), distinguish_badger_path(distinguish_badger))
			.col-md-8
				.details
					%p
						%b= distinguish_badger.start_date
					%p
						= distinguish_badger.full_name
					%p 
						%b Organization:
						= distinguish_badger.organization
					%p 
						%b Designation:
						= distinguish_badger.designation
					%p.photostream
						= distinguish_badger.linkedin_url
						%br
						= distinguish_badger.philanthropy_url
						%br
					%p
						= distinguish_badger.biography

app/views/distinguish_badgers/show.html.haml
Comming Soon

app/views/events/_buttons.html.haml
.share
  <span class='st_facebook_hcount' displayText='Facebook'></span>
  <span class='st_twitter_hcount' displayText='Tweet'></span>
  <span class='st_linkedin_hcount' displayText='LinkedIn'></span>

app/views/events/_event.html.haml
.row.event
  .col-md-4
    - if event.photo.exists?
      .image
        = link_to(image_tag(event.photo.url(:medium)), event_path(event))
  .col-md-8
    .details
      %p
        %b= event.short_event_date
      %h2= event.title
      %p
        %b= event.speaker
      %p
        Host:
        = event.host_name
      %p.location
        - if event.venue_street_address.present?
          = link_to event.venue_name, event.map_link
        %br
        = event.full_address
      - if event.photo_album_url.present?
        %p.photostream
          = link_to "View photos from this event", event.photo_album_url

app/views/events/index.html.haml
= content_for :title, 'Bay Area Badger Distinguished Alumni Award Winners'
%h1 Events
.events
  = render events

app/views/events/show.html.haml
=content_for :title do
  = event.title

=content_for :head do
  %meta{property: 'og:url',         content: "#{event_url(event)}" }
  %meta{property: 'og:title',       content: "#{event.title}" }
  %meta{property: 'og:site_name',   content: 'Badger Entrepreneurship Forum' }
  %meta{property: 'og:description', content: "#{event.truncate_desc}" }
  %meta{property: 'og:type',        content: 'website' }
  - if event.photo.exists?
    %meta{property: 'og:image',     content: "#{event.photo.url(:thumb)}"  }
  - else
    %meta{property: 'og:image',     content: "BascomHall.jpg" }

%h1=event.title
%p
  %b= event.speaker
- if event.photo.exists?
  .image
    = image_tag event.photo.url(:large)
.details
  %p
    %b= event.short_event_date
  = event.description.html_safe
  - if event.photo_album_url.present?
    %p.photostream
      = link_to "View photos from this event", event.photo_album_url
  %hr
  = render partial: 'events/buttons', locals: {event: event}
  %hr

  %p
    Host:
    = event.host_name
  %p.location
    = event.venue_name
    %br
    = event.full_address
  - if event.venue_street_address.present?
    = link_to event.venue_name, event.map_link

app/views/layouts/application.html.haml
!!!
%html
  %head
    = content_for?(:head) ? yield(:head) : ''
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1.0"}
    %title= content_for :title || 'Bay Area Badger Distinguished Alumni Award Winners'
    / %title= content_for?(:title) ? yield(:title) : "Bay Area Badger Distinguished Alumni Award Winners"
    %meta{:content => content_for?(:description) ? yield(:description) : "The Badger Entrepreneurship Forum (BEF) is an organization of the University of Wisconsin Alumni in the San Francisco Bay Area interested in promoting and supporting the University and its alumni.", :name => "description"}
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    = stylesheet_link_tag :application, :media => "all"
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "aca95b21-8b4e-49d6-bfad-fa35b59d6fe4", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  %body
    = render 'shared/navbar'
    - if current_page?(root_path)
      #main{:role => "main"}
        = render 'shared/messages'
        = yield
    - else
      .container
        #main{:role => "main"}
          = render 'shared/messages'
          = yield
  %footer
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

app/views/people/index.html.haml
= content_for :title, 'Bay Area Badger Distinguished Alumni Award Winners'
%h1 Who are the Badgers?
.tags
  = link_to 'All', people_path, class: tag_title.blank? ? 'active' : ''
  - tags.each do |available_tag|
    |
    = link_to available_tag.title, people_path(tag_title: available_tag.title), class: tag_title == available_tag.title ? 'active' : ''

.row
  - people.each do |person|
    %span.col-md-4
      .card
        .content
          .left-side
            =image_tag(person.photo.url(:thumb), class: 'profile')
            - if person.linkedin_url.present?
              = link_to image_tag('linkedin.png', class: 'linkedin-img'), person.linkedin_url

          .right-side
            %p.name= person.full_name
            %p.title= person.title
            %p.business= person.organization

app/views/people/mentors.html.haml
= content_for :title, 'Bay Area Badger Distinguished Alumni Award Winners'
%h1 Badger Mentors
.row
  - badger_mentors.each do |person|
    %span.col-md-4
      .card
        .content
          .left-side
            =image_tag(person.photo.url(:thumb), class: 'profile')
            - if person.linkedin_url.present?
              = link_to image_tag('linkedin.png', class: 'linkedin-img'), person.linkedin_url

          .right-side
            %p.name= person.full_name
            %p.title= person.title
            %p.business= person.organization

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-collapse'}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: '/'}
    .navbar-collapse.collapse
      %ul.nav.navbar-nav#menu-main
        = nav_link_to 'Home', root_path
        = nav_link_to 'Events', events_path
        = nav_link_to 'Distinguish Badgers', distinguish_badgers_path
        = nav_link_to 'Badgers', people_path
        = nav_link_to 'Mentors', mentors_path
        = nav_link_to 'About', about_path
        /= nav_link_to 'Contact', contact_path

app/views/welcome/_contact.html.haml
%h1 Contact Us
.row
  .col-md-4
    %p
      To contact us please e-mail the following address
      = mail_to 'info@siliconvalleybadgers.com'
  .col-md-8
    = image_tag('BascomHall.jpg', size: '450x300')

app/views/welcome/about.html.haml
= content_for :title, 'Bay Area Badger Distinguished Alumni Award Winners'
%h1 About

%p The Badger Entrepreneurship Forum (BEF) was started in 2009 by Pavan Nigam and David Bunzel, both graduates of the University of Wisconsin.  Pavan, a Bay Area-based serial entrepreneur (founder/CTO Healtheon/WebMD, founder/CEO Cendura, founder/CEO Trackle), joined the University of Wisconsin Board of Visitors in 2007, and soon got re-immersed in the Badger world.  David, the founder and CEO of DigitalMediaIX, has been very active with the Bay Area Badger community.  He also has been very involved with start-up companies.  David has founded and advised companies in the personal computer hardware and software business, Web 1.0, and Web 2.0 markets.  In addition, he has led three industry standards organizations, focusing on optical storage, physical/logical security, and smart energy.

%p Pavan and David recognized that the Bay Area had a significant number of very successful Badgers – entrepreneurs, CEOs, executives, venture capitalists, attorneys, investment bankers and consultants. In addition, there were a number of UW graduates involved in starting their own companies.   This led to the idea behind the Badger Entrepreneurship Forum where Badgers could leverage from each other’s experiences and networks.

%p The group holds events every 2-3 months and speakers are drawn from Badgers involved with different segments of the entrepreneurial ecosystem. Past speakers have included entrepreneurs, public company CEOs, investment bankers, and venture capitalists.


%h2 Board
.row
  - board_members.each do |person|
    %span.col-md-4
      .card
        .content
          .left-side
            =image_tag(person.photo.url(:thumb), class: 'profile')
            - if person.linkedin_url.present?
              = link_to image_tag('linkedin.png', class: 'linkedin-img'), person.linkedin_url

          .right-side
            %p.name= person.full_name
            %p.title= person.title
            %p.business= person.organization
%br
%br
%br

= render 'welcome/contact'

app/views/welcome/contact.html.haml
%h1 Contact Us
.row
  .col-md-4
    %p
      To contact us please e-mail the following address
      = mail_to 'info@siliconvalleybadgers.com'
  .col-md-8
    = image_tag('BascomHall.jpg', size: '450x300')

app/views/welcome/index.html.erb
Badgers

app/views/welcome/index.html.haml
= content_for :title, 'Bay Area Badger Distinguished Alumni Award Winners'
- if event
  #headerwrap{style: "background: url(#{event.photo.url(:huge)}); -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;"}
    %header.clearfix
      .container
        %article
          .event
            %p.talk-speaker= event.speaker
            %p.talk-title= event.title
            %p.talk-date= event.starts_at
            - if event.host_name.present?
              %p.talk-sponsor
                %span.host Host:
                = event.host_name
            - if event.venue_name.present?
              %p.talk-location
                %span.venue Venue:
                %b= event.venue_name
            .more
              - if !event.past?
                %span.rsvp
                  = link_to 'RSVP', event.rsvp_url
              = link_to 'Read More', event_path(event)



.scrollblock
  %section#feature
    .container
      %article
        %p
          The Badger Entrepreneurship Forum (BEF) is an organization of the University of Wisconsin Alumni in the San Francisco Bay Area interested in promoting and supporting the University and its alumni.

%section#prev-speaker.single-page.scrollblock
  .container
    %h1 Previous Events
    .row
      - past_events.each do |event|
        %span.col-md-4
          %article.post
            = link_to(image_tag(event.photo.url(:medium), class: 'img-prev-speakers'), event_path(event))
            .inside
              %p.prev-speaker= event.speaker
              %p.prev-title= event.title
              %p.prev-date= event.short_event_date
              %p.prev-sponsor= event.host_name